title: Welcome to my blog!
author: Bora KIŞ
email: izzetkis@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  I was born on October 4, 1998 in Ankara. After completing my primary
  and high school education here, I was entitled to enter the
  Department of Biomedical Engineering at Düzce University in 2016
  and still continue my education life. I will complete my undergraduate
  period in June 2020. I am particularly interested in machine learning,
  deep learning, artificial intelligence, digital signal
  processing and image processing.

# social links
twitter_username: izzetborakis
github_username:  BoraKis

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
